# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"addition": "00_core.ipynb",
         "multiplication": "00_core.ipynb"}

modules = ["math.py"]

doc_url = "https://muellerzr.github.io/testing/"

git_url = "https://github.com/muellerzr/testing/tree/master/"

def custom_doc_links(name): return None
