# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['addition', 'multiplication']

# Cell
def addition(a:int,b:int) -> int:
    """
    Performs addition of `a` and `b`
    """
    return a + b

# Internal Cell
def _subtraction(a:int, b:int) -> int:
    """
    Performs subtraction of `a` and `b`
    """
    return a + b

# Cell
def multiplication(a:int, b:int) -> int:
    """
    Performs multiplication of `a` and `b`
    """
    return a * b